services:
  openwakeword-jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - jupyter-data:/root/.jupyter
      - model-cache:/root/.cache
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - openwakeword-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  jupyter-data:
  model-cache:

networks:
  openwakeword-network:
    driver: bridge